"""ISO 14224 equipment family definitions.

Config-driven controlled vocabularies for iso_equipment_class,
subunit_type_code, and component_type_code per equipment family.
"""

EQUIPMENT_FAMILIES = {
    "EF-ROT": {
        "name": "Rotating equipment",
        "description": "Pumps, compressors, turbines, fans",
        "equipment_classes": [
            "CENTRIFUGAL_PUMP",
            "RECIP_COMPRESSOR",
            "CENTRIFUGAL_COMPRESSOR",
            "GAS_TURBINE",
            "STEAM_TURBINE",
            "FAN",
        ],
        "subunit_types": [
            "DRIVER",
            "PUMP_COMP_SECTION",
            "SEAL_SYSTEM",
            "BEARING_SYSTEM",
            "LUBE_OIL_SYSTEM",
            "COOLING_SYSTEM",
            "COUPLING",
        ],
        "component_types": [
            "BEARING_RADIAL",
            "BEARING_THRUST",
            "SEAL_MECH",
            "SEAL_PACKING",
            "IMPELLER",
            "ROTOR",
            "GEAR",
            "OIL_PUMP",
            "COOLER",
            "FILTER",
            "MOTOR_STATOR",
            "MOTOR_ROTOR",
            "COUPLING_ELEMENT",
        ],
    },
    "EF-STAT": {
        "name": "Static equipment",
        "description": "Vessels, exchangers, columns, tanks",
        "equipment_classes": [
            "PRESSURE_VESSEL",
            "HEAT_EXCHANGER",
            "COLUMN",
            "TANK",
        ],
        "subunit_types": [
            "SHELL",
            "HEAD",
            "NOZZLE",
            "INTERNALS",
            "SUPPORT",
            "INSULATION",
        ],
        "component_types": [
            "TRAY",
            "PACKING",
            "TUBE",
            "BUNDLE",
            "MANWAY",
            "NOZZLE_NECK",
            "SUPPORT_BEAM",
            "RELIEF_DEVICE",
        ],
    },
    "EF-ELEC": {
        "name": "Electrical equipment",
        "description": "Transformers, switchgear, motors, generators",
        "equipment_classes": [
            "TRANSFORMER",
            "SWITCHGEAR",
            "MCC",
            "GENERATOR",
            "MOTOR",
        ],
        "subunit_types": [
            "PRIMARY_WINDING",
            "SECONDARY_WINDING",
            "COOLING_SYSTEM",
            "TAP_CHANGER",
            "BUSBAR",
            "BREAKER_CELL",
            "CONTROL_CUBICLE",
            "STATOR",
            "ROTOR",
            "TERMINAL_BOX",
        ],
        "component_types": [
            "BREAKER",
            "CONTACTOR",
            "FUSE",
            "CT",
            "VT",
            "BUSHING",
            "FAN",
            "OIL_PUMP",
            "INSULATION_BLOCK",
        ],
    },
    "EF-INST": {
        "name": "Instrumentation and control",
        "description": "Valves, transmitters, PLCs, analyzers",
        "equipment_classes": [
            "CONTROL_VALVE",
            "ONOFF_VALVE",
            "TRANSMITTER",
            "PLC",
            "ANALYZER",
            "DETECTOR",
        ],
        "subunit_types": [
            "ACTUATOR",
            "VALVE_BODY",
            "POSITIONER",
            "SENSOR",
            "ELECTRONICS_MODULE",
            "ENCLOSURE",
        ],
        "component_types": [
            "STEM",
            "TRIM",
            "SEAT",
            "PACKING",
            "SENSING_ELEMENT",
            "PCB",
            "POWER_SUPPLY",
            "TERMINAL_BLOCK",
        ],
    },
    "EF-SAFE": {
        "name": "Safety systems",
        "description": "ESD, fire and gas, relief, deluge",
        "equipment_classes": [
            "ESD_SYSTEM",
            "FIRE_GAS_SYSTEM",
            "RELIEF_VALVE",
            "DELUGE_SYSTEM",
        ],
        "subunit_types": [
            "LOGIC_SOLVER",
            "IO_MODULE",
            "FIELD_LOOP",
            "DETECTION_LAYER",
            "VALVE_ASSEMBLY",
        ],
        "component_types": [
            "ESD_VALVE",
            "SOLENOID",
            "DETECTOR_GAS",
            "DETECTOR_SMOKE",
            "RELIEF_DISC",
            "SPRINKLER_NOZZLE",
        ],
    },
    "EF-PACK": {
        "name": "Packages and skids",
        "description": "Packaged compressors, pumps, gensets",
        "equipment_classes": [
            "PACKAGE_COMPRESSOR",
            "PACKAGE_PUMP",
            "GENSET_SKID",
        ],
        "subunit_types": [
            "DRIVER",
            "COMPRESSOR_PUMP",
            "BASEFRAME",
            "LUBE_OIL_SYSTEM",
            "CONTROL_PANEL",
            "ANCILLARIES",
        ],
        "component_types": [],
    },
}

PROCESS_TEMPLATES = {
    "PF-WELL": {
        "name": "Wells and wellheads",
        "facility_types": ["WELL_CLUSTER", "WELL_PAD"],
        "system_types": ["WELLHEAD", "XMT", "ARTIFICIAL_LIFT", "FLOWLINE"],
    },
    "PF-SURF": {
        "name": "Surface processing and compression",
        "facility_types": ["OFFSHORE_PLATFORM", "CPF"],
        "system_types": [
            "SEPARATION",
            "GAS_COMPRESSION",
            "OIL_EXPORT",
            "GAS_DEHYDRATION",
            "FLARE",
            "METERING",
        ],
    },
    "PF-UTIL": {
        "name": "Utilities and power",
        "facility_types": [],
        "system_types": [
            "INSTR_AIR",
            "ELEC_DIST",
            "COOL_WATER",
            "FIRE_WATER",
            "HVAC",
            "DIESEL_GEN",
        ],
    },
    "PF-PIPE": {
        "name": "Subsea and export (optional phase)",
        "facility_types": [],
        "system_types": [
            "OIL_PIPE",
            "GAS_PIPE",
            "UMBILICAL",
            "RISER",
            "MANIFOLD",
        ],
    },
}
